### ISSUE TITLE
Default message for t out somewhat misleading

### ISSUE THREAD

**Issue by smcabrera** [samg/timetrap#105]
This is may be a bit nitpicky, but it seems to me that from a usability perspective the message that you receive after the command t out is a bit misleading:

```
t out
checked out of sheet 'current-sheet'
```

Based on this message, it'd be easy to think that you're gonna need to check into the _sheet_ again if you want to interact further with it, like this:

```
t sheet current-sheet
```

This is not the case however. Here, 'current-sheet' remains the current sheet for purposes of editing entries, checking back into the most recent entry with resume, timesheet list, etc. Is there any way in which you are actually checked out of the sheet that I'm missing? 

If not, perhaps it would be more accurate to say that you're not "in" the _entry_ rather than the sheet (unless I'm misunderstanding something and there's another way in which you've left the sheet).

Might it be more accurate to have a message like this?

```
checked out of entry "notes for entry"
```

Let me know what you think--I'd be happy to submit a pull request.

**Comment by categulario** [comment]
@pepe 's proposal seems very reasonable.
