### ISSUE TITLE
Newline for 't now' while not tracking

### ISSUE THREAD

**Issue by qmanjr5** [samg/timetrap#106]
When I'm checked into a timesheet, doing echo -n $(t n) (or some variations thereof) result in no newline at the end, as I want. 
However, when you're currently not checked into a sheet, the newline is still there

**Comment by categulario** [comment]
internally the function `puts` is used. Try this:

```ruby
#cosa.rb
puts "hello"
```

then

```bash
echo -n $(ruby cosa.rs)
```

I'll close this for now
