### ISSUE TITLE
"t last week" would be useful

### ISSUE THREAD

**Issue by kevinior** [samg/timetrap#107]
I often need to check times from the previous week and "t disp --start='last monday' --end='last friday'" is more typing than I'd like.

How about either "last" as a prefix for the "week" and "month" shortcuts or a "--last" option for them?

**Comment by tekknolagi** [comment]
So something like `t disp --start='last week'`? Or do you mean `t disp 'last week`?

**Comment by tekknolagi** [comment]
Incidentally, you can make a shell alias until it's fixed:

`alias tlastweek="t disp --start='last monday' --end='last friday'"`

**Comment by kevinior** [comment]
`t disp last week` would be especially handy for me but I suppose that might make handling the command-line arguments ugly. `t week --last` would work too.

I'd guess that people often want to see the previous/week month (especially when entering hours into another system) so the less typing involved the better.

**Comment by tekknolagi** [comment]
I tried hacking in a sort of "modifier" thing for week, month, etc but it's not super pretty. I'll post the diff somewhere.

**Comment by tekknolagi** [comment]
https://gist.github.com/tekknolagi/1c8deb93148a624bfc2e

**Comment by kevinior** [comment]
That looks great, although I'm not qualified to judge prettiness of Ruby code :smile:

**Comment by categulario** [comment]
`t week` is available in recent versions, closing for now
