### ISSUE TITLE
Option to resume a task by "id"

### ISSUE THREAD

**Issue by beloso** [samg/timetrap#114]
Currently you can only resume the last logged task.

It would be cool to have the possibility to resume any existing task.

Example:
User is working on "task A"
User switches to "task B"
User wants to continue on "Task A"

**Comment by marcaddeo** [comment]
Would love to see this feature added... I'm starting to use timetrap in my workflow and writing a lot of scripts around it to simplify, so I may take a crack at this at some point..

**Comment by samg** [comment]
It'd be great to see a PR for this. Thanks!

**Comment by patrickdavey** [comment]
Can this issue be closed now? @marcaddeo @samg ?
