### ISSUE TITLE
Install timetrap locally could not find sequel

### ISSUE THREAD

**Issue by nowox** [samg/timetrap#119]
I just installed sequel but I cannot install timetrap. What is the problem? 

```
$ gem install --local sequel-4.28.0.gem
Successfully installed sequel-4.28.0
Parsing documentation for sequel-4.28.0
Done installing documentation for sequel after 12 seconds
1 gem installed

$ gem install --local timetrap-1.9.0.gem
ERROR:  Could not find a valid gem 'sequel' (~> 4.0.0) in any repository
```

But sequel is available: 

```
$ irb
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> require 'erb'
=> true
irb(main):003:0> require 'sequel'
=> true
irb(main):004:0> require 'chronic'
=> true
irb(main):005:0> require 'sequel/extensions/inflector'
=> true
```

**Comment by samg** [comment]
Timetrap is looking for a version of Sequel in the 4.0.X range.  You have a more recent version installed.  You should be able to get it to work by installing Sequel 4.0.0 or by removing the `--local` flag and running `gem install timetrap`

**Comment by jostber** [comment]
I package timetrap for slackbuilds and also sequel. It seems like timetrap only works with sequel 4.0.0 so this needs to be installed as well, as it does not work with sequel 4.42.0. Could this be more flexible?

**Comment by dechimp** [comment]
Trying to help clean up old issues. Sequel 4.43+ is the constraint for the latest timetrap.  Let me know if you want this reopened.
