### ISSUE TITLE
ID for timesheets

### ISSUE THREAD

**Issue by jostber** [samg/timetrap#12]
A feature that would be great was if all timesheets had an ID as well, like:

[1] Project_1
[2] Project_2
[3] L_A_H
[4] P69991

Then it could be possible to change to a timesheet like this:

t s 4

Would be a bit quicker on the command line.

**Comment by categulario** [comment]
another possible solution, using [fzf](https://github.com/junegunn/fzf):

```bash
t s $(t s | tail -n +2 | grep -Eo '^.{1}\w*' | sed -E 's/^.{1}//' | fzf)
```
