### ISSUE TITLE
t kill documentation seems misleading

### ISSUE THREAD

**Issue by henry-bennett** [samg/timetrap#120]
```
* kill - Delete a timesheet or an entry.
    usage: t kill [--id ID] [TIMESHEET]
    -i, --id <id:i>           Alter entry with id <id> instead of the running entry
```

The sentence about the `--id` option seems to imply that if you leave off the option, the running entry will be killed.  However, that is not what happens:

```
$ t kill
can't find "" to kill
```

I am new to using this program so maybe I am misunderstanding.

**Comment by samg** [comment]
WIthout the `--id` flag `kill` assumes you want to delete a whole sheet (and in this case is looking for a sheet named "").  I agree the docs could probably be improved.  If you'd want to PR a doc change I could review and see about getting it merged.
