### ISSUE TITLE
Feature request: Auto checkout on system sleep

### ISSUE THREAD

**Issue by fredcallaway** [samg/timetrap#121]
I'm completely naive to low level system behavior, so forgive my ignorance if this is impossible...

Would it be possible to configure time trap to automatically checkout of all running activities upon system sleep? This saves the trouble of explicitly checking out before leaving your computer, and the hassle of fixing it when you forget.

Many thanks!

**Comment by samg** [comment]
This probably isn't something that could be provided by timetrap itself, though it looks like there are tools that allow you to run a command on system sleep.  [This Stack Exchange post](http://apple.stackexchange.com/questions/27036/possible-to-run-scripts-on-sleep-and-wake) could be a good place to start.

If you can get one of those set up you might be able to run `t out` when your computer suspends and get the behavior you want.

**Comment by fredcallaway** [comment]
Thanks for the pointer!

I was able to accomplish this with [sleepwatcher](http://www.bernhard-baehr.de).
