### ISSUE TITLE
Error installing timetrap

### ISSUE THREAD

**Issue by GrouchyGaijin** [samg/timetrap#124]
I'm running Ubuntu 14.04 with ruby from the repository
Today is Mon Feb 22 @ 15:38:22 ~/timetrap $ sudo gem install timetrapBuilding native extensions.  This could take a while...
ERROR:  Error installing timetrap:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:3:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/sqlite3-1.3.11 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/sqlite3-1.3.11/ext/sqlite3/gem_make.out

**Comment by samg** [comment]
Looks like some problem compiling the sqlite dependency.  You probably need to make sure you have a working C compiler installed. `apt-get install build-essentials` I think.  

Closing since this is an issues installing sqlite3 gem rather than timetrap itself.

**Comment by janswist** [comment]
This helped me: https://stackoverflow.com/a/51932169/2570350 (for Mac below, for Ubuntu inside the link)

```
gem install sqlite3 -- --with-sqlite3-lib=/usr/lib
```
