### ISSUE TITLE
fix day formatter

### ISSUE THREAD

**Issue by dantiel** [samg/timetrap#129]
in formatter i had to replace the " === " comparison in line 34 by ".cover? ".

**Comment by dantiel** [comment]
(without quotes)

**Comment by samg** [comment]
Could you open this issue agains the https://github.com/samg/timetrap_formatters repo, which is the home of the day formatter?  Also it would be useful to provide some more detail on why you think this change was necessary (e.g. error message, ruby version, etc.) or to open a PR with the suggested change.  Thanks!
