### ISSUE TITLE
Show entry ids by default (--ids)

### ISSUE THREAD

**Issue by naps62** [samg/timetrap#132]
I mostly use `t t` and `t y` to check today's timesheet, and to check & submit the one from yesterday.

But when I have to edit an entry before submitting, it would be useful to already know it's id. Right now, I'm forced to re-run the command with `--ids` so that I can then `edit` it

Is there anything I can add to the configuration YML file so that IDs are always shown by default?

**Comment by samg** [comment]
You could do this by writing a custom formatter and setting it as the `default_formatter`.
https://github.com/samg/timetrap#custom-formatters
https://github.com/samg/timetrap#configuration
(it'd also be possible to set `default_command` to `t d --ids` so `t` displays your desired output)

It also would be pretty easy to add a new config value to the configuration system through a PR. 
https://github.com/samg/timetrap/blob/master/lib/timetrap/config.rb

**Comment by categulario** [comment]
seems solved
