### ISSUE TITLE
Set start of week

### ISSUE THREAD

**Issue by namdnguyen** [samg/timetrap#141]
It would be useful to be able to set what day starts the week for `t week`. Monday appears to be the default, but allowing a configuration variable like `week_start: Sunday` in the .timetrap.yml file would be great.

**Comment by samg** [comment]
Sounds like a good improvement.  It would be pretty easy to hook this into the config system so the Monday default could be overridden.

**Comment by namdnguyen** [comment]
Hey @samg. Hopefully, you haven't already worked on this. I thought I would take a stab at this as my first contribution to an open source project. It did seem to be pretty easy, as you mentioned. I'll submit a pull request soon, if you could still use it.

**Comment by samg** [comment]
Sounds great. Thanks!

**Comment by namdnguyen** [comment]
I'll be submitting the pull request from my fork, but I had a question about squash merging. It seems like you are using squash merging or your collaborators are squashing when they submit. I don't have any interesting history with this, anyways, just typo fixes and testing. 

Should I squash my history in this feature branch (set_week_start) or can I submit the branch to you and you'll be able to squash merge it into the master branch?

**Comment by samg** [comment]
I don't have any strong preference about how the commits are structured or
squashed.
