### ISSUE TITLE
Update sequel dependency to version 4.4.0

### ISSUE THREAD

**Issue by rubik** [samg/timetrap#156]
In Ruby 2.4.0, the old version of sequel gives annoying warnings about `Fixnum` and `Bignum`, which in the newer version of Ruby were unified into `Integer`:
```
$ t s
/home/user/.gem/ruby/2.4.0/gems/sequel-4.0.0/lib/sequel/database/schema_generator.rb:19: warning: constant ::Fixnum is deprecated
/home/user/.gem/ruby/2.4.0/gems/sequel-4.0.0/lib/sequel/database/schema_generator.rb:19: warning: constant ::Bignum is deprecated
 Timesheet      Running     Today       Total Time
 [...]
```

The last version of sequel fixes these.

**Comment by dashkb** [comment]
lol https://github.com/samg/timetrap/pull/155... @samg isn't ultra-responsive

**Comment by jostber** [comment]
Sequel is regularily updated, now in version 5.0.0. What about leaving this version dependency open so timetrap works with all versions?

**Comment by jostber** [comment]
Any news on this? I am packing timetrap for SlackBuild and the old sequel dependency gives a run error.

**Comment by dashkb** [comment]
Sounds like a good idea; I'd suggest opening the PR so if @samg thinks it's a good idea he can just merge it.

**Comment by berkes** [comment]
I've updated all dependencies and fixed the issues from that in https://github.com/samg/timetrap/pull/180
