### ISSUE TITLE
force stop active entry on start a new one

### ISSUE THREAD

**Issue by rogelio-meza-t** [samg/timetrap#157]
Hey guys!

It is possible start a new entry and (force) stop the active entry?
now I'm doing something like this `t out && t in new task`

Maybe something like `t in --force new task` would be fine

**Comment by namdnguyen** [comment]
Hi @rogelio-meza-t, this feature is already built into timetrap. You may need to edit your configuration file `.timetrap.yml`, which should be in your home directory, by setting `auto_checkout` to `true`. 

Then each time you `t in` or `t r` a new entry, timetrap should automatically checkout of your currently running entry.

**Comment by jostber** [comment]
Seems like this can be closed as well.
