### ISSUE TITLE
't display' returns...

### ISSUE THREAD

**Issue by sakhan007** [samg/timetrap#158]
https://pastebin.com/FwXXFuSk

**Comment by patrickdavey** [comment]
What version of Ruby are you using? Timetrap supports the versions in the [.travis.yml](https://github.com/samg/timetrap/blob/master/.travis.yml), which is 

- 2.1.8
- 2.2.4
- 2.3.3
- 2.4.0

**Comment by sakhan007** [comment]
Thanks!!

**Comment by patrickdavey** [comment]
@sakhan007 does this mean that you were using an older version of Ruby which is unsupported?

If so, can you mark this issue as Closed?

**Comment by sakhan007** [comment]
Was using an old unsupported Ruby version.
