### ISSUE TITLE
Longest note length working?

### ISSUE THREAD

**Issue by jostber** [samg/timetrap#160]
Is it possible to set this parameter in .timetrap.yml to control the notes length? 

longest_note_length: 200

I have set this, but the notes length is the standard in 1.14.1.

**Comment by patrickdavey** [comment]
Not currently no, this configuration was never set.

Currently [is it used here in the text formatter](https://github.com/samg/timetrap/blob/8a3ecf3443625f6ae5aac02c00c3f7d37f93c5e9/lib/timetrap/formatters/text.rb#L61-L65) you could easily make a copy of that formatter and set the `LONGEST_NOTE_LENGTH` to be whatever you like.

You can send a Pull Request with the functionality and tests of course :)

**Comment by jostber** [comment]
Setting it in the text formatter works well, thanks. Could be useful to have it as a config though.
