### ISSUE TITLE
`invalid date` output when outputting week shortcut

### ISSUE THREAD

**Issue by nuudles** [samg/timetrap#161]
Ever since the PR #141 was merged, it looks like typing `t w all` seems to be broken for me. `t d -s "Monday" all` still works fine.

```
» t w all 
invalid date
```

My `.timetrap.yml` has `week_start: Monday` defined.

**Comment by samg** [comment]
Looks like there was a bug which broke `t w` at the end of the month.  It should be fixed by 729513c and in gem https://rubygems.org/gems/timetrap/versions/1.15.1.

Thanks!
