### ISSUE TITLE
Error for ' t d -f ical'

### ISSUE THREAD

**Issue by nixbytes** [samg/timetrap#163]
Hello
Love the app, it is super useful. their issue in which I am having on OSX

we I run `t d -f ical`
`undefined method `dtstart' for #<Timetrap::Formatters::Ical:0x007fdb7b9e5e18>`

when i check the file it creates, their is no data.

so I re-install the gem icalendar and tried icalendar2.

any ideas what could be the cause:?

**Comment by samg** [comment]
My guess would be there's an incompatibility between recent versions of the icalendar gem and timetrap.  The icalendar functionality is [tested against icalendar version 1.3](https://github.com/samg/timetrap/blob/master/timetrap.gemspec#L26), which is very old, but may do what you want.  I'd recommend downgrading your icalendar gem to the 1.3 series to see if that solves the problem.  It'd also be possible to update timetrap to work with newer versions of icalendar, though I won't have time to do that in the foreseeable future.  I'd happily accept a pull request for it though.
