### ISSUE TITLE
"Time to work" per day and Status

### ISSUE THREAD

**Issue by solars** [samg/timetrap#17]
Hi again,

One more thing, in my quick and dirty timesheet app I included the following:

I specify the duration of a common work day in my config, e.g. 8 hours
And in addition I have something like "t status" which returns:
Working (4:31 worked, -3:29 left) or
Paused (4:31 worked, -3:29 left)

And the same for the week in "t display"
This lets me:
a) quickly estimate over-hours and when I can leave the office :)
b) I'm using the status (Working/Paused) in my taskbar, so I can imedeately see if the timer is running and if not, click on the taskbar to start it.

Very useful in my opinion

**Comment by categulario** [comment]
closing because it has no comments in the last 7 years
