### ISSUE TITLE
What happens when there are more than 10000 entries?

### ISSUE THREAD

**Issue by namdnguyen** [samg/timetrap#172]
I noticed that there are 4 character spaces when showing IDs in a display command before you get to a sheet name. What happens when you have 10000 or more entries? Does timetrap continue expanding the length for formatting IDs? 6 digits will be shown at 100000 and so on?

**Comment by jerith666** [comment]
I haven't gotten up to six digits yet but I'm well into the five-digit range, and it seems to work okay:

```
$ t display --ids --start today email | head -4
Timesheet: email
Id    Day                Start      End        Duration   Notes
31378 Thu Nov 08, 2018   08:40:01 - 08:44:56   0:04:55    
31402                    15:48:07 - 15:50:43   0:02:36    
```

**Comment by namdnguyen** [comment]
That's good to know. I forgot that I was viewing with the `by_day` formatter, too. If I run into any problems at 5 digits, I'll take a look there. Thanks for confirming! I'll close this issue.
