### ISSUE TITLE
Timetrap fails with recent sqlite3

### ISSUE THREAD

**Issue by jostber** [samg/timetrap#177]
Timetrap gives this error if running with new sqlite3 v.1.4.0:

Traceback (most recent call last):
        8: from /usr/bin/t:23:in `<main>'
        7: from /usr/lib64/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
        6: from /usr/lib64/ruby/2.6.0/rubygems.rb:303:in `synchronize'
        5: from /usr/lib64/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
        4: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        3: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        2: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        1: from /usr/lib64/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/usr/lib64/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'sqlite3' (~> 1.3.3) - did find: [sqlite3-1.4.0] (Gem::MissingSpecVersionError)

**Comment by jostber** [comment]
Changing to "s.add_runtime_dependency(%q<sqlite3>.freeze, ["~> 1.4.0"])" in 
/usr/lib64/ruby/gems/2.6.0/specifications/timetrap-1.15.1.gemspec works.

**Comment by berkes** [comment]
I've updated all dependencies and fixed the issues from that in https://github.com/samg/timetrap/pull/180
