### ISSUE TITLE
Autocomplete script assumes ~./timetrap.db existence

### ISSUE THREAD

**Issue by vcavallo** [samg/timetrap#189]
`timetrap.yml` allows setting arbitrary locations for the db file. This is wonderful. However, if you _have_ used a different location for your db file, you'll get an error upon trying to trigger autocompletion, as the `timetrap-autocomplete.bash` file [assumes that the database file resides](https://github.com/samg/timetrap/blob/master/completions/bash/timetrap-autocomplete.bash#L7) at `~/.timetrap.db`. 

The simplest way to address this for now is probably just to add a line to the README suggesting that users symlink their non-standard db file location to their home directory.  
Hopefully I have time today to open that PR.

**Comment by categulario** [comment]
Hey @vcavallo I made a little change in the bash completion script. Please check if that solves the issue for you.

**Comment by categulario** [comment]
Bash autocomplete no longer asumes the location of the database file. Solved in e7e0bbee577901c7a97fc724788c8c28d2dcddc2
