### ISSUE TITLE
Invalid byte sequence in UTF 8

### ISSUE THREAD

**Issue by MariusBasse** [samg/timetrap#192]
Hey team, 

when I want to print my current sheet, the sheet is unavailable and I get an "invalid byte sequence in UTF 8" error. Where is my current sheet located so that I can at least write it down and look at it and reinstall timetrap?

**Comment by dechimp** [comment]
Typically upgrading / reinstalling timetrap doesnt affect or delete your database, but if I were worried about it, I would make a backup, which I think is located at ~/.timetrap.db

**Comment by dechimp** [comment]
and I think the database is SQLite, so you can query it if need be.
`$ sqlite3 ~/.timetrap.db`
`SELECT * from entries WHERE sheet like 'mySheet';`

**Comment by categulario** [comment]
Hey  @MariusBasse do you have a traceback of the error? Did you find the cause?
