### ISSUE TITLE
List previous months

### ISSUE THREAD

**Issue by CharcoGreen** [samg/timetrap#199]
Hi , I can't view resume of previous months.
Is normal or i'm not doing well?

```bash
t month --start april --format csv
start,end,note,sheet
```

Regards

**Comment by categulario** [comment]
I confirm that the behaviour is inconsistent, without the `--start` specifier it works. Let me check.

**Comment by categulario** [comment]
@CharcoGreen try running with `--start 'last april'` instead. Currenlty just writing `april` resolves to april of the next year

**Comment by CharcoGreen** [comment]
> @CharcoGreen try running with `--start 'last april'` instead. Currenlty just writing `april` resolves to april of the next year

@categulario  hat's working to me.
Thanks
