### ISSUE TITLE
Configure option for forced rounding UP

### ISSUE THREAD

**Issue by npostulart** [samg/timetrap#46]
Is it possible to tell timetrap on round to always rounding up?

I sometimes have very small time entries and want to round it up to 5 minutes duration. I configured timetrap to round on 300 seconds but on small entries i inly get 0:00:00.

**Comment by kristian-94** [comment]
I would have use for this functionality too. I want to be able to round a 5 minute phone call up to 15min for the purposes of billing. 1hr5min should be rounded to 1hr15min as well.
If I worked on this in a PR to timetrap core would you consider adding it?

**Comment by samg** [comment]
@kristian-94 - Yes I would definitely consider adding this.  I think this could also be achieved using a custom formatter (see https://github.com/samg/timetrap_formatters) which might be an easier path.
