### ISSUE TITLE
Select sheet based on `pwd`

### ISSUE THREAD

**Issue by TSFoster** [samg/timetrap#69]
I'm pretty sure I'm going to do this for me anyway, but I just wanted to see if it was something you would pull if I sent a request.

I'd like to use specific sheets when I'm in certain directories. Say you want to use the sheet "Secret Project" when you're in `~/projects/secret/`. Timetrap would work as usual everywhere else, but when you're running it from within `~/projects/secret/` it will check in to and out of "Secret Project".

I'm not quite sure how I'd do this yet, maybe a local `.timetrap` file with just the name of the sheet to use.

**Comment by FellowMD** [comment]
@samg This issue can be closed as it's been implemented and merged in
